<?php

namespace RavenDB\Type;

class ExtendedArrayObject extends \ArrayObject implements \JsonSerializable
{
    protected function validateValue($value): void
    {
    }

    public function offsetSet($key, $value)
    {
        $this->validateValue($value);
        parent::offsetSet($key, $value); // TODO: Change the autogenerated stub
    }

    public function prepend($value): void
    {
        $this->validateValue($value);

        $currentArray = $this->getArrayCopy();
        array_unshift($currentArray, $value);

        $this->exchangeArray($currentArray);
    }

    public function removeValue($value): void
    {
        if(($key = array_search($value, $this->getArrayCopy(), true)) !== FALSE) {
            $this->offsetUnset($key);
        }
    }

    public function clear(): void
    {
        foreach ($this as $key => $value) {
            $this->offsetUnset($key);
        }
    }

    public function isEmpty(): bool
    {
        return $this->count() == 0;
    }

    public function isNotEmpty(): bool
    {
        return $this->count() > 0;
    }

    public function first()
    {
        return $this->offsetGet(array_key_first($this->getArrayCopy()));
    }

    public function last()
    {
        return $this->offsetGet(array_key_last($this->getArrayCopy()));
    }

    public function jsonSerialize(): array
    {
        return $this->getArrayCopy();
    }
}
