<?php

namespace RavenDB\Documents\Indexes\Spatial;

class SpatialBounds
{
    private float $minX;
    private float $maxX;
    private float $minY;
    private float $maxY;

    public function getMinX(): float
    {
        return $this->minX;
    }

    public function setMinX(float $minX): void
    {
        $this->minX = $minX;
    }

    public function getMaxX(): float
    {
        return $this->maxX;
    }

    public function setMaxX(float $maxX): void
    {
        $this->maxX = $maxX;
    }

    public function getMinY(): float
    {
        return $this->minY;
    }

    public function setMinY(float $minY): void
    {
        $this->minY = $minY;
    }

    public function getMaxY(): float
    {
        return $this->maxY;
    }

    public function setMaxY(float $maxY): void
    {
        $this->maxY = $maxY;
    }

    public function __construct(float $minX, float $minY, float $maxX, float $maxY)
    {
        $this->minX = $minX;
        $this->maxX = $maxX;
        $this->minY = $minY;
        $this->maxY = $maxY;
    }

//  @todo: remove later this - autogenerated java code for HashMap that we don't need in PHP
//
//        @Override
//        public int hashCode() {
//            return new HashCodeBuilder().append(maxX).append(maxY).append(minX).append(minY).hashCode();
//        }
//
//        @Override
//        public boolean equals(Object obj) {
//            if (this == obj)
//                return true;
//            if (obj == null)
//                return false;
//            if (getClass() != obj.getClass())
//                return false;
//            SpatialBounds other = (SpatialBounds) obj;
//            return new EqualsBuilder().append(maxX, other.maxX).append(maxY, other.maxY).append(minX, other.minX).append(minY, other.minY).isEquals();
//        }
//
}
